config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  GUESTS = (1..12).to_a
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
  validates :number_of_guests, inclusion: { in: GUESTS }
  validates :number_of_guests, numericality: { only_integer: true }
  validates :price_per_night, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.create(flat_params)
    redirect_to flats_path
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests, :collection => Flat::GUESTS %>
  <%= f.submit "I'm done!" %>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <h1>Edit your flat</h1>

  <%= render "form", flat: @flat %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All our flats (<%= @flats.count %>)</h1>

  <ul class="flexy">
    <% @flats.each do |flat| %>
      <li>
        <div>
          <img src="https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80">
        </div>
        <div class="pad-10 card-mg card-title">
          <%= flat.name %>
        </div>

        <div class="pad-10 card-mg">
          <p><i class="fas fa-map-marker-alt"></i> <%= flat.address %></p>
        </div>

        <div class="pad-10 card-mg block-in">
          <p><i class="fas fa-user"></i> <%= flat.number_of_guests %></p>
          <p><i class="fas fa-euro-sign"></i> <%= flat.price_per_night %></p>
        </div>

        <div class="pad-10 card-mg card-bottom">
          <%= link_to "More info", flat_path(flat) %>
          <%= link_to "Edit", edit_flat_path(flat) %>
          <%= link_to "Remove", flat_path(flat),
                method: :delete,
                data: { confirm: "Are you sure?" }%>
        </div>

      </li>
    <% end %>
  </ul>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add your flat</h1>

  <%= render "form", flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="container">
  <h1><%= @flat.name %></h1>

  <p><strong>Address:</strong> <%= @flat.address %></p>
  <p><strong>Description:</strong> <%= @flat.description %></p>
  <p><strong>Price per night:</strong> <%= @flat.price_per_night %></p>
  <p><strong>Number of guests:</strong> <%= @flat.number_of_guests %></p>

  <p><%= link_to "Edit flat", edit_flat_path(@flat) %></p>
  <p><%= link_to "Delete #{@flat.name}",
                flat_path(@flat),
                method: :delete,
                data: { confirm: "Are you sure?" } %></p>
  <p><%= link_to "Back to list", flats_path%></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <p><%= link_to "Simple Airbnb", flats_path %></p>
      <%= link_to "Add a flat", new_flat_path %>
    </div>
    <%= yield %>
  </body>
</html>